# 单元测试用例
[TOC]
## 概述
在Rust里面最常用的判断运算结果是否正取的方式是使用`assert_eq!`这个宏，比如下面：
```rust
let one_plus_one = stringify!(1 + 1);
assert_eq!(one_plus_one, "1 + 1");
```

如果故意把比对的值写错，编译的时候就会出现错误

```shell
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"1 + 1"`,
 right: `"1 + 2"`', src/main.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

开发的时候使用`assert_eq!`很方便。不过开发完了记得把这些语句删除掉。

Edsger W. Dijkstra在他1972年的文章《The Humble Programmer》（《谦卑的程序员》）中说：“Program testing can be a very effective way to show the presence of bugs, but it is hopelessly inadequate for showing their absence.”[^1] 但是这句话并不是说我们不应该做程序测试。

我们程序中的正确性是指我们的代码在多大程度上完成了我们想要做的事情。Rust的设计高度关注程序的正确性，但正确性很复杂，不容易证明。Rust的类型系统承担了这一重任，但类型系统无法捕捉每一种不正确的情况。因此，Rust包括支持在语言中编写自动软件测试。

举个例子，比如说我们写了一个叫做add_two的函数，该函数在传递给它的任何数字上加2。这个函数的签名接受一个整数作为参数，并返回一个整数作为结果。当我们实现和编译这个函数时，Rust会做所有你已经学过的类型检查和借贷检查，以确保，例如，我们没有向这个函数传递一个String值或一个无效的引用。但是Rust不能检查这个函数是否能准确地完成我们的意图，也就是返回参数加2，而不是参数加10或参数减50！这就是测试的作用。这就是测试的作用。

我们可以编写测试来断言，例如，当我们向add_two函数传递3时，返回值是5。

测试是一项复杂的技能：尽管我们不能在一章中涵盖关于如何写好测试的每个细节，但我们将讨论Rust的测试设施的机制。我们将讨论在编写测试时可用的注释和宏，为运行测试提供的默认行为和选项，以及如何将测试组织成单元测试和集成测试。

## 如何编写测试
Rust函数测试，用于验证非测试代码是否以预期方式运行。测试函数的主体通常执行以下三个动作：

- 设置任何需要的数据或状态。
- 运行你要测试的代码。
- 断言结果是你所期望的。

## 测试函数的解剖
最简单地说，Rust中的测试是一个带有测试属性的函数。要把一个函数变成一个测试函数，在fn前的一行加上`#[test]`。 当你用cargo test命令运行你的测试时，Rust会建立一个测试文件，运行用测试属性注释的函数，并报告每个测试函数的通过或失败。

当我们用`Cargo`制作一个新的库项目时，会自动为我们生成一个包含测试函数的测试模块。这个模块可以帮助你开始编写你的测试，这样你就不必每次开始新项目时都要查找测试函数的确切结构和语法。只要你想，你可以添加更多的测试函数和更多的测试模块。

我们将通过试验为我们生成的模板测试来探索测试工作的一些方面，而不需要实际测试任何代码。然后我们将编写一些真实世界的测试，调用我们编写的一些代码，并断言其行为是正确的。

让我们创建一个名为adder的新库项目:

```shell
$ cargo new adder --lib
     Created library `adder` project
$ cd adder
```
src/lib.rs
```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

```shell
$ cargo test
   Compiling adder v0.1.0 (/home/sunny/project/rust/bible/src/chapter05/sunny_test01/adder)
    Finished test [unoptimized + debuginfo] target(s) in 0.46s
     Running target/debug/deps/adder-c1b75f7bf9fed63b

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

```

再添加一个测试用例：

```rust
#[test]
fn exploration() {
    assert_eq!(2 * 2, 4);
}
```
运行一下
```shell
$ cargo test
   Compiling adder v0.1.0 (/home/sunny/project/rust/bible/src/chapter05/sunny_test01/adder)
    Finished test [unoptimized + debuginfo] target(s) in 0.27s
     Running target/debug/deps/adder-c1b75f7bf9fed63b

running 2 tests
test tests::exploration ... ok
test tests::it_works ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

下面我们写一个失败的例子：

```rust
#[test]
fn do_fail() {
    assert_eq!(2 -2, 4);
}
```
运行一下
```shell
running 3 tests  三个失败1个
test tests::exploration ... ok
test tests::do_fail ... FAILED
test tests::it_works ... ok

failures:

---- tests::do_fail stdout ----
thread 'tests::do_fail' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `4`', src/lib.rs:15:9
 failures:
    tests::do_fail
```

再写一个失败的例子：
```rust
#[test]
fn another() {
    panic!("Make this test fail");
}
```

运行一下：

```shell
running 4 tests  四个失败2个
test tests::exploration ... ok
test tests::another ... FAILED
test tests::do_fail ... FAILED
test tests::it_works ... ok

failures:

---- tests::another stdout ----
thread 'tests::another' panicked at 'Make this test fail', src/lib.rs:20:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::do_fail stdout ----
thread 'tests::do_fail' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `4`', src/lib.rs:15:9


failures:
    tests::another
    tests::do_fail
```

## 注释

[^1]: 我试着翻译一下:程序测试可能是显示错误存在的一种非常有效的方法，但是它不足以显示所有错误的存在。